import type { EventEffect, HistoricalEvent, Policy } from './types';

// Dates are historical. Effect sizes (severity, factor, weeks, tariff rate) are modelling
// estimates: tariff rates are approximate trade-weighted averages (PIIE tracker), not the
// headline rate on a single list of goods.

const wiki = (...pages: string[]) =>
  pages.map((page) => `https://en.wikipedia.org/wiki/${page}`).join(' ; ');
const IMF = (country: string) => `https://www.imf.org/en/Countries/${country}`;
const TARIFF_SOURCE = `${wiki('China%E2%80%93United_States_trade_war')} ; https://www.piie.com/research/piie-charts/us-china-trade-war-tariffs-date-chart`;

const event = (
  id: string,
  [year, month, day]: readonly [number, number, number],
  bri: boolean,
  actors: readonly string[],
  effects: readonly EventEffect[],
  source: string,
): HistoricalEvent => ({
  id,
  date: { year, month, day },
  bri,
  actors,
  effects,
  provenance: 'historical',
  source,
});

const announcement = (topic: string): EventEffect => ({ kind: 'announcement', topic });
const policy = (actor: string, name: Policy): EventEffect => ({
  kind: 'policy',
  actor,
  policy: name,
});
const tradeShock = (scope: string, factor: number, weeks: number): EventEffect => ({
  kind: 'trade-shock',
  scope,
  factor,
  weeks,
});
const tariffs = (usOnChina: number, chinaOnUs: number): readonly EventEffect[] => [
  { kind: 'tariff', by: 'USA', on: 'CHN', rate: usOnChina },
  { kind: 'tariff', by: 'CHN', on: 'USA', rate: chinaOnUs },
];
const attackOnChineseWorkers = (region: string, severity: number): EventEffect => ({
  kind: 'security-attack',
  region,
  target: 'chinese-workers',
  severity,
});

const G7_PARTNERS = ['USA', 'GBR', 'JPN', 'DEU', 'EU'] as const;
const WESTERN_SANCTIONERS = ['USA', 'EU', 'GBR', 'JPN'] as const;

export const EVENTS: readonly HistoricalEvent[] = [
  event(
    'astana-speech',
    [2013, 9, 7],
    true,
    ['CHN', 'KAZ'],
    [announcement('silk-road-economic-belt')],
    wiki('Belt_and_Road_Initiative', 'Silk_Road_Economic_Belt'),
  ),
  event(
    'jakarta-speech',
    [2013, 10, 3],
    true,
    ['CHN'],
    [announcement('maritime-silk-road')],
    wiki('21st_Century_Maritime_Silk_Road', 'Belt_and_Road_Initiative'),
  ),
  event(
    'crimea-sanctions',
    [2014, 3, 17],
    false,
    ['RUS', 'USA', 'EU'],
    [{ kind: 'sanctions', target: 'RUS', by: ['USA', 'EU'], severity: 0.05 }],
    wiki(
      'Annexation_of_Crimea_by_the_Russian_Federation',
      'International_sanctions_during_the_Russo-Ukrainian_War',
    ),
  ),
  event(
    'russia-sectoral-sanctions',
    [2014, 7, 29],
    false,
    ['RUS', 'USA', 'EU'],
    [{ kind: 'sanctions', target: 'RUS', by: ['USA', 'EU'], severity: 0.15 }],
    wiki('International_sanctions_during_the_Russo-Ukrainian_War', 'Malaysia_Airlines_Flight_17'),
  ),
  event(
    'oil-price-crash',
    [2014, 11, 27],
    false,
    ['SAU', 'RUS', 'KAZ', 'AZE', 'IRN'],
    [
      tradeShock('RUS', 0.85, 104),
      tradeShock('KAZ', 0.85, 104),
      tradeShock('AZE', 0.8, 104),
      tradeShock('IRN', 0.9, 104),
    ],
    wiki('2010s_oil_glut', '2014%E2%80%932016_Russian_financial_crisis'),
  ),
  event(
    'silk-road-fund',
    [2014, 12, 29],
    true,
    ['CHN'],
    [policy('CHN', 'silk-road-fund')],
    wiki('Silk_Road_Fund'),
  ),
  event(
    'eaeu-launch',
    [2015, 1, 1],
    false,
    ['RUS', 'KAZ', 'BLR'],
    [announcement('eaeu-launch')],
    wiki('Eurasian_Economic_Union'),
  ),
  event(
    'cpec-launch',
    [2015, 4, 20],
    true,
    ['CHN', 'PAK'],
    [announcement('cpec')],
    wiki('China%E2%80%93Pakistan_Economic_Corridor'),
  ),
  event(
    'greece-capital-controls',
    [2015, 6, 29],
    false,
    ['GRC', 'EU'],
    [policy('GRC', 'capital-controls'), { kind: 'debt-distress', country: 'GRC', severity: 0.8 }],
    wiki('Greek_government-debt_crisis', '2015_Greek_bailout_referendum'),
  ),
  event(
    'tenge-float',
    [2015, 8, 20],
    false,
    ['KAZ'],
    [announcement('tenge-float'), tradeShock('KAZ', 0.85, 52)],
    wiki('Kazakhstani_tenge'),
  ),
  event(
    'aiib-founded',
    [2015, 12, 25],
    true,
    ['CHN', 'IND', 'RUS', 'DEU', 'GBR'],
    [policy('CHN', 'aiib')],
    wiki('Asian_Infrastructure_Investment_Bank'),
  ),
  event(
    'jcpoa-implementation',
    [2016, 1, 16],
    false,
    ['IRN', 'USA', 'EU'],
    [{ kind: 'sanctions-eased', target: 'IRN', by: ['USA', 'EU'] }],
    wiki('Joint_Comprehensive_Plan_of_Action'),
  ),
  event(
    'china-railway-express',
    [2016, 6, 8],
    true,
    ['CHN', 'KAZ', 'RUS', 'BLR', 'POL', 'DEU'],
    [announcement('china-europe-rail-subsidies')],
    wiki('China_Railway_Express', 'Belt_and_Road_Initiative'),
  ),
  event(
    'turkey-coup-attempt',
    [2016, 7, 15],
    false,
    ['TUR'],
    [{ kind: 'conflict', country: 'TUR', severity: 0.3, weeks: 2 }],
    wiki('2016_Turkish_coup_attempt'),
  ),
  event(
    'cosco-piraeus',
    [2016, 8, 10],
    true,
    ['CHN', 'GRC'],
    [announcement('piraeus-cosco')],
    wiki('Port_of_Piraeus', 'COSCO_Shipping'),
  ),
  event(
    'egypt-float-imf',
    [2016, 11, 11],
    false,
    ['EGY'],
    [
      { kind: 'imf-program', country: 'EGY', amountBn: 12 },
      { kind: 'debt-distress', country: 'EGY', severity: 0.3 },
      tradeShock('EGY', 0.85, 26),
    ],
    `${wiki('Egyptian_pound', 'Economy_of_Egypt')} ; ${IMF('EGY')}`,
  ),
  event(
    'uzbekistan-opening',
    [2016, 12, 14],
    false,
    ['UZB'],
    [announcement('uzbek-opening')],
    wiki('Economy_of_Uzbekistan', 'Uzbekistani_som'),
  ),
  event(
    'first-brf',
    [2017, 5, 14],
    true,
    ['CHN', 'RUS', 'KAZ', 'UZB', 'BLR', 'POL', 'TUR', 'PAK', 'GRC'],
    [announcement('belt-and-road-forum')],
    wiki('Belt_and_Road_Forum'),
  ),
  event(
    'sco-india-pakistan',
    [2017, 6, 9],
    false,
    ['IND', 'PAK'],
    [
      { kind: 'bloc-join', country: 'IND', bloc: 'SCO' },
      { kind: 'bloc-join', country: 'PAK', bloc: 'SCO' },
    ],
    wiki('Shanghai_Cooperation_Organisation'),
  ),
  event(
    'hambantota-lease',
    [2017, 7, 29],
    true,
    ['CHN'],
    [announcement('debt-trap-debate')],
    wiki('Hambantota_International_Port', 'Debt-trap_diplomacy'),
  ),
  event(
    'btk-railway',
    [2017, 10, 30],
    false,
    ['AZE', 'TUR'],
    [announcement('btk-railway')],
    wiki('Baku%E2%80%93Tbilisi%E2%80%93Kars_railway'),
  ),
  event(
    'us-leaves-jcpoa',
    [2018, 5, 8],
    false,
    ['USA', 'IRN'],
    [{ kind: 'sanctions', target: 'IRN', by: ['USA'], severity: 0.3 }],
    wiki('United_States_withdrawal_from_the_Joint_Comprehensive_Plan_of_Action'),
  ),
  event(
    'us-china-tariffs-2018',
    [2018, 7, 6],
    false,
    ['USA', 'CHN'],
    tariffs(0.12, 0.18),
    TARIFF_SOURCE,
  ),
  event(
    'turkish-lira-crisis',
    [2018, 8, 10],
    false,
    ['TUR', 'USA'],
    [announcement('lira-crisis'), tradeShock('TUR', 0.85, 26)],
    wiki('2018_Turkish_currency_and_debt_crisis'),
  ),
  event(
    'iran-sanctions-snapback',
    [2018, 11, 5],
    false,
    ['USA', 'IRN'],
    [
      { kind: 'sanctions', target: 'IRN', by: ['USA'], severity: 0.6 },
      tradeShock('IRN', 0.75, 104),
    ],
    wiki('United_States_withdrawal_from_the_Joint_Comprehensive_Plan_of_Action'),
  ),
  event(
    'italy-joins-bri',
    [2019, 3, 23],
    true,
    ['CHN', 'EU'],
    [announcement('italy-bri-mou')],
    wiki('Belt_and_Road_Initiative', 'China%E2%80%93Italy_relations'),
  ),
  event(
    'second-brf',
    [2019, 4, 25],
    true,
    ['CHN', 'RUS', 'KAZ', 'UZB', 'BLR', 'AZE', 'PAK', 'EGY', 'GRC'],
    [announcement('belt-and-road-forum'), policy('CHN', 'green-bri')],
    wiki('Belt_and_Road_Forum'),
  ),
  event(
    'pakistan-imf-2019',
    [2019, 7, 3],
    false,
    ['PAK'],
    [
      { kind: 'imf-program', country: 'PAK', amountBn: 6 },
      { kind: 'debt-distress', country: 'PAK', severity: 0.4 },
    ],
    `${IMF('PAK')} ; ${wiki('Economy_of_Pakistan')}`,
  ),
  event(
    'us-china-tariffs-2019',
    [2019, 9, 1],
    false,
    ['USA', 'CHN'],
    tariffs(0.21, 0.22),
    TARIFF_SOURCE,
  ),
  event(
    'power-of-siberia',
    [2019, 12, 2],
    false,
    ['RUS', 'CHN'],
    [announcement('power-of-siberia')],
    wiki('Power_of_Siberia'),
  ),
  event(
    'wuhan-lockdown',
    [2020, 1, 23],
    false,
    ['CHN'],
    [{ kind: 'pandemic', severity: 0.5, weeks: 130 }, tradeShock('CHN', 0.75, 8)],
    wiki('COVID-19_pandemic_in_mainland_China', 'COVID-19_pandemic'),
  ),
  event(
    'brexit',
    [2020, 1, 31],
    false,
    ['GBR', 'EU'],
    [{ kind: 'bloc-leave', country: 'GBR', bloc: 'EU' }],
    wiki('Brexit'),
  ),
  event(
    'khorgos-covid-closure',
    [2020, 2, 1],
    false,
    ['KAZ', 'CHN'],
    [{ kind: 'route-disruption', node: 'khorgos', factor: 0.6, weeks: 10 }],
    wiki('COVID-19_pandemic_in_Kazakhstan', 'Khorgos'),
  ),
  event(
    'covid-lockdowns',
    [2020, 3, 11],
    false,
    ['CHN', 'USA', 'EU', 'IND'],
    [tradeShock('world', 0.85, 13)],
    wiki('COVID-19_lockdowns', 'COVID-19_pandemic'),
  ),
  event(
    'ever-given',
    [2021, 3, 23],
    false,
    ['EGY'],
    [{ kind: 'route-disruption', node: 'suez-canal', factor: 0, weeks: 1 }],
    wiki('2021_Suez_Canal_obstruction'),
  ),
  event(
    'b3w',
    [2021, 6, 12],
    false,
    [...G7_PARTNERS],
    [policy('USA', 'b3w')],
    wiki('Build_Back_Better_World'),
  ),
  event(
    'dasu-attack',
    [2021, 7, 14],
    true,
    ['PAK', 'CHN'],
    [attackOnChineseWorkers('PAK-REST', 0.5)],
    wiki('Dasu_Hydropower_Project', 'Terrorism_in_Pakistan'),
  ),
  event(
    'no-new-coal-abroad',
    [2021, 9, 21],
    true,
    ['CHN'],
    [policy('CHN', 'no-new-coal-abroad')],
    wiki('Belt_and_Road_Initiative', 'Coal_in_China'),
  ),
  event(
    'small-and-beautiful',
    [2021, 11, 19],
    true,
    ['CHN'],
    [policy('CHN', 'small-and-beautiful')],
    wiki('Belt_and_Road_Initiative'),
  ),
  event(
    'global-gateway',
    [2021, 12, 1],
    false,
    ['EU'],
    [policy('EU', 'global-gateway')],
    wiki('Global_Gateway'),
  ),
  event(
    'kazakhstan-unrest',
    [2022, 1, 2],
    false,
    ['KAZ', 'RUS'],
    [{ kind: 'conflict', country: 'KAZ', severity: 0.4, weeks: 2 }],
    wiki('2022_Kazakh_unrest'),
  ),
  event(
    'russia-invades-ukraine',
    [2022, 2, 24],
    false,
    ['RUS', 'BLR', ...WESTERN_SANCTIONERS],
    [
      { kind: 'conflict', country: 'RUS', severity: 0.3, weeks: 200 },
      { kind: 'sanctions', target: 'RUS', by: WESTERN_SANCTIONERS, severity: 0.6 },
      { kind: 'sanctions', target: 'BLR', by: WESTERN_SANCTIONERS, severity: 0.4 },
      tradeShock('world', 0.95, 26),
    ],
    wiki('Russian_invasion_of_Ukraine', 'International_sanctions_during_the_Russo-Ukrainian_War'),
  ),
  event(
    'karachi-university-attack',
    [2022, 4, 26],
    true,
    ['PAK', 'CHN'],
    [{ kind: 'security-attack', region: 'PAK-SIN', target: 'chinese-teachers', severity: 0.4 }],
    wiki('Balochistan_Liberation_Army', 'Terrorism_in_Pakistan'),
  ),
  event(
    'uflpa-in-force',
    [2022, 6, 21],
    false,
    ['USA', 'CHN'],
    [policy('USA', 'uflpa-import-ban')],
    wiki('Uyghur_Forced_Labor_Prevention_Act'),
  ),
  event(
    'pgii',
    [2022, 6, 26],
    false,
    [...G7_PARTNERS],
    [policy('USA', 'pgii')],
    wiki('Partnership_for_Global_Infrastructure_and_Investment'),
  ),
  event(
    'pakistan-floods',
    [2022, 8, 25],
    false,
    ['PAK'],
    [
      { kind: 'disaster', region: 'PAK-SIN', hazard: 'flood', severity: 0.9 },
      { kind: 'disaster', region: 'PAK-BAL', hazard: 'flood', severity: 0.8 },
      { kind: 'disaster', region: 'PAK-REST', hazard: 'flood', severity: 0.5 },
      tradeShock('PAK', 0.9, 26),
    ],
    wiki('2022_Pakistan_floods'),
  ),
  event(
    'turkey-earthquake',
    [2023, 2, 6],
    false,
    ['TUR'],
    [{ kind: 'disaster', region: 'TUR-REST', hazard: 'earthquake', severity: 0.9 }],
    wiki('2023_Turkey%E2%80%93Syria_earthquakes'),
  ),
  event(
    'iran-joins-sco',
    [2023, 7, 4],
    false,
    ['IRN', 'IND'],
    [{ kind: 'bloc-join', country: 'IRN', bloc: 'SCO' }],
    wiki('Shanghai_Cooperation_Organisation'),
  ),
  event(
    'pakistan-imf-sba',
    [2023, 7, 12],
    false,
    ['PAK'],
    [
      { kind: 'imf-program', country: 'PAK', amountBn: 3 },
      { kind: 'debt-distress', country: 'PAK', severity: 0.7 },
    ],
    `${IMF('PAK')} ; ${wiki('Economy_of_Pakistan')}`,
  ),
  event(
    'imec',
    [2023, 9, 9],
    false,
    ['USA', 'IND', 'SAU', 'ARE', 'EU', 'DEU'],
    [
      policy('USA', 'imec'),
      policy('IND', 'imec'),
      policy('SAU', 'imec'),
      policy('ARE', 'imec'),
      policy('EU', 'imec'),
    ],
    wiki('India%E2%80%93Middle_East%E2%80%93Europe_Economic_Corridor'),
  ),
  event(
    'third-brf',
    [2023, 10, 17],
    true,
    ['CHN', 'RUS', 'KAZ', 'UZB', 'PAK'],
    [announcement('belt-and-road-forum')],
    wiki('Belt_and_Road_Forum'),
  ),
  event(
    'houthi-attacks-begin',
    [2023, 11, 19],
    false,
    ['EGY'],
    [{ kind: 'route-disruption', node: 'bab-el-mandeb', factor: 0.8, weeks: 4 }],
    wiki('Red_Sea_crisis'),
  ),
  event(
    'italy-exits-bri',
    [2023, 12, 6],
    true,
    ['CHN', 'EU'],
    [announcement('italy-bri-exit')],
    wiki('Belt_and_Road_Initiative', 'China%E2%80%93Italy_relations'),
  ),
  event(
    'red-sea-diversions',
    [2023, 12, 18],
    false,
    ['EGY', 'USA', 'GBR'],
    [
      { kind: 'route-disruption', node: 'bab-el-mandeb', factor: 0.3, weeks: 100 },
      { kind: 'route-disruption', node: 'suez-canal', factor: 0.5, weeks: 100 },
      tradeShock('EGY', 0.9, 100),
    ],
    wiki('Red_Sea_crisis', 'Operation_Prosperity_Guardian'),
  ),
  event(
    'egypt-ras-el-hekma-imf',
    [2024, 3, 6],
    false,
    ['EGY', 'ARE'],
    [
      announcement('ras-el-hekma'),
      { kind: 'imf-program', country: 'EGY', amountBn: 8 },
      { kind: 'debt-distress', country: 'EGY', severity: 0.4 },
    ],
    `${wiki('Economy_of_Egypt', 'Egyptian_pound')} ; ${IMF('EGY')}`,
  ),
  event(
    'besham-attack',
    [2024, 3, 26],
    true,
    ['PAK', 'CHN'],
    [attackOnChineseWorkers('PAK-REST', 0.5)],
    wiki('Dasu_Hydropower_Project', 'Terrorism_in_Pakistan'),
  ),
  event(
    'belarus-joins-sco',
    [2024, 7, 4],
    false,
    ['BLR', 'KAZ'],
    [{ kind: 'bloc-join', country: 'BLR', bloc: 'SCO' }],
    wiki('Shanghai_Cooperation_Organisation'),
  ),
  event(
    'karachi-airport-attack',
    [2024, 10, 6],
    true,
    ['PAK', 'CHN'],
    [attackOnChineseWorkers('PAK-SIN', 0.4)],
    wiki('Balochistan_Liberation_Army', 'Terrorism_in_Pakistan'),
  ),
  event(
    'us-china-tariffs-2025',
    [2025, 4, 9],
    false,
    ['USA', 'CHN'],
    tariffs(1.25, 1.25),
    TARIFF_SOURCE,
  ),
  event(
    'geneva-tariff-truce',
    [2025, 5, 14],
    false,
    ['USA', 'CHN'],
    tariffs(0.51, 0.33),
    TARIFF_SOURCE,
  ),
];
