import type { CivilDate } from '../core/calendar';
import type { Project } from './types';

const wiki = (...pages: string[]) =>
  pages.map((page) => `https://en.wikipedia.org/wiki/${page}`).join(' ; ');

const date = (year: number, month: number, day: number): CivilDate => ({ year, month, day });

// Costs and loans in USD billions. Interest: Chinese policy-bank concessional loans ~2%,
// commercial loans (CPEC power plants, LIBOR + margin) ~4.5–5%, 0 for equity or grants.
// `bri` asks whether the project would be missing in a world without the Belt and Road:
// Chinese finance, contractors or equity committed after 2013. Middle Corridor links built
// with Azerbaijani, Kazakh, Turkmen, Iranian or Japanese money are `bri: false`, as are
// Chinese deals signed long before 2013 and the Russia–China Power of Siberia gas deal.
export const PROJECTS: readonly Project[] = [
  {
    id: 'khorgos-gateway-dry-port',
    kind: 'dry-port',
    country: 'KAZ',
    region: 'KAZ-ALA',
    bri: true,
    sponsor: 'KAZ',
    lenders: [],
    costBn: 0.25,
    loanBn: 0,
    interestRate: 0,
    announced: date(2014, 1, 15),
    constructionStart: date(2014, 6, 1),
    opened: date(2015, 8, 1),
    jobs: { construction: 1200, operation: 600, localShare: 0.9 },
    co2KtPerYear: 10,
    landHa: 130,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Khorgos_Gateway', 'Khorgas'),
  },
  {
    id: 'kuryk-port',
    kind: 'port',
    country: 'KAZ',
    region: 'KAZ-AKT',
    bri: false,
    sponsor: 'KAZ',
    lenders: [],
    costBn: 0.25,
    loanBn: 0,
    interestRate: 0,
    announced: date(2013, 12, 1),
    constructionStart: date(2014, 9, 1),
    opened: date(2016, 12, 1),
    jobs: { construction: 1200, operation: 400, localShare: 1 },
    co2KtPerYear: 10,
    landHa: 150,
    displacedPeople: 0,
    opensLinks: ['aktau~kuryk~rail', 'kuryk~baku-alat~sea'],
    provenance: 'estimated',
    source: wiki('Kuryk', 'Trans-Caspian_International_Transport_Route'),
  },
  {
    id: 'angren-pap-railway',
    kind: 'rail',
    country: 'UZB',
    region: 'UZB-FER',
    bri: true,
    sponsor: 'CHN',
    lenders: ['china-exim', 'world-bank'],
    costBn: 1.6,
    loanBn: 0.545,
    interestRate: 0.02,
    announced: date(2013, 6, 18),
    constructionStart: date(2013, 7, 1),
    opened: date(2016, 6, 22),
    jobs: { construction: 5000, operation: 400, localShare: 0.75 },
    co2KtPerYear: 5,
    landHa: 400,
    displacedPeople: 0,
    opensLinks: ['tashkent~andijan~rail'],
    provenance: 'estimated',
    source: wiki('Angren–Pap_railway'),
  },
  {
    id: 'kti-railway',
    kind: 'rail',
    country: 'KAZ',
    region: 'KAZ-AKT',
    bri: false,
    sponsor: 'KAZ',
    lenders: ['isdb'],
    costBn: 1.2,
    loanBn: 0.37,
    interestRate: 0.03,
    announced: date(2007, 5, 1),
    constructionStart: date(2007, 12, 1),
    opened: date(2014, 12, 3),
    jobs: { construction: 8000, operation: 1000, localShare: 1 },
    co2KtPerYear: 30,
    landHa: 3700,
    displacedPeople: 0,
    opensLinks: ['aktau~tehran~rail'],
    provenance: 'estimated',
    source: wiki(
      'Kazakhstan–Turkmenistan–Iran_railway',
      'International_North–South_Transport_Corridor',
    ),
  },
  {
    id: 'baku-tbilisi-kars-railway',
    kind: 'rail',
    country: 'TUR',
    region: 'TUR-KAR',
    bri: false,
    sponsor: 'AZE',
    lenders: ['sofaz'],
    costBn: 1.1,
    loanBn: 0.775,
    interestRate: 0.04,
    announced: date(2007, 2, 7),
    constructionStart: date(2007, 11, 21),
    opened: date(2017, 10, 30),
    jobs: { construction: 5000, operation: 600, localShare: 1 },
    co2KtPerYear: 20,
    landHa: 500,
    displacedPeople: 0,
    opensLinks: ['tbilisi~kars~rail'],
    provenance: 'estimated',
    source: wiki('Baku–Tbilisi–Kars_railway'),
  },
  {
    id: 'baku-alat-port',
    kind: 'port',
    country: 'AZE',
    region: 'AZE-BAK',
    bri: false,
    sponsor: 'AZE',
    lenders: [],
    costBn: 0.6,
    loanBn: 0,
    interestRate: 0,
    announced: date(2007, 3, 18),
    constructionStart: date(2010, 11, 1),
    opened: date(2018, 5, 14),
    jobs: { construction: 3000, operation: 1000, localShare: 1 },
    co2KtPerYear: 30,
    landHa: 400,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Port_of_Baku', 'Alat_Free_Economic_Zone'),
  },
  {
    id: 'gwadar-port',
    kind: 'port',
    country: 'PAK',
    region: 'PAK-BAL',
    bri: true,
    sponsor: 'CHN',
    lenders: ['china-mofcom'],
    costBn: 1,
    loanBn: 0.3,
    interestRate: 0,
    announced: date(2013, 2, 18),
    constructionStart: date(2016, 9, 1),
    opened: date(2018, 1, 29),
    jobs: { construction: 3000, operation: 1000, localShare: 0.55 },
    co2KtPerYear: 20,
    landHa: 925,
    displacedPeople: 500,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Gwadar_Port', 'China–Pakistan_Economic_Corridor'),
  },
  {
    id: 'kkh-havelian-thakot',
    kind: 'road',
    country: 'PAK',
    region: 'PAK-REST',
    bri: true,
    sponsor: 'CHN',
    lenders: ['china-exim'],
    costBn: 1.3,
    loanBn: 1.1,
    interestRate: 0.02,
    announced: date(2015, 4, 20),
    constructionStart: date(2016, 9, 1),
    opened: date(2020, 7, 28),
    jobs: { construction: 7000, operation: 200, localShare: 0.8 },
    co2KtPerYear: 5,
    landHa: 700,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Karakoram_Highway', 'Hazara_Motorway'),
  },
  {
    id: 'sahiwal-coal',
    kind: 'power-coal',
    country: 'PAK',
    region: 'PAK-PUN',
    bri: true,
    sponsor: 'CHN',
    lenders: ['icbc'],
    costBn: 1.8,
    loanBn: 1.44,
    interestRate: 0.05,
    announced: date(2014, 11, 8),
    constructionStart: date(2015, 7, 31),
    opened: date(2017, 7, 3),
    jobs: { construction: 5000, operation: 700, localShare: 0.65 },
    co2KtPerYear: 7500,
    landHa: 280,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Sahiwal_Coal_Power_Project'),
  },
  {
    id: 'port-qasim-coal',
    kind: 'power-coal',
    country: 'PAK',
    region: 'PAK-SIN',
    bri: true,
    sponsor: 'CHN',
    lenders: ['china-exim'],
    costBn: 2.09,
    loanBn: 1.56,
    interestRate: 0.05,
    announced: date(2015, 4, 20),
    constructionStart: date(2015, 5, 1),
    opened: date(2018, 4, 25),
    jobs: { construction: 6000, operation: 800, localShare: 0.6 },
    co2KtPerYear: 7500,
    landHa: 200,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Port_Qasim', 'China–Pakistan_Economic_Corridor'),
  },
  {
    id: 'lahore-orange-line',
    kind: 'metro',
    country: 'PAK',
    region: 'PAK-PUN',
    bri: true,
    sponsor: 'CHN',
    lenders: ['china-exim'],
    costBn: 1.63,
    loanBn: 1.55,
    interestRate: 0.02,
    announced: date(2014, 5, 20),
    constructionStart: date(2015, 10, 1),
    opened: date(2020, 10, 25),
    jobs: { construction: 7000, operation: 1500, localShare: 0.85 },
    co2KtPerYear: 20,
    landHa: 70,
    displacedPeople: 2000,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Orange_Line_(Lahore_Metro)'),
  },
  {
    id: 'piraeus-cosco',
    kind: 'port',
    country: 'GRC',
    region: 'GRC-PIR',
    bri: true,
    sponsor: 'CHN',
    lenders: [],
    costBn: 0.73,
    loanBn: 0,
    interestRate: 0,
    announced: date(2016, 1, 20),
    constructionStart: date(2016, 8, 10),
    opened: date(2016, 8, 10),
    jobs: { construction: 1000, operation: 3000, localShare: 0.97 },
    co2KtPerYear: 60,
    landHa: 0,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Port_of_Piraeus', 'Piraeus_Port_Authority'),
  },
  {
    id: 'great-stone-park',
    kind: 'industrial-zone',
    country: 'BLR',
    region: 'BLR-MSQ',
    bri: true,
    sponsor: 'CHN',
    lenders: ['china-exim'],
    costBn: 1.2,
    loanBn: 0.5,
    interestRate: 0.03,
    announced: date(2011, 9, 18),
    constructionStart: date(2014, 6, 19),
    opened: date(2015, 5, 12),
    jobs: { construction: 3000, operation: 3000, localShare: 0.85 },
    co2KtPerYear: 150,
    landHa: 11250,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('China–Belarus_Industrial_Park'),
  },
  {
    id: 'yamal-lng',
    kind: 'lng',
    country: 'RUS',
    region: 'RUS-REST',
    bri: true,
    sponsor: 'RUS',
    lenders: ['china-exim', 'cdb'],
    costBn: 27,
    loanBn: 12,
    interestRate: 0.045,
    announced: date(2013, 9, 5),
    constructionStart: date(2013, 12, 18),
    opened: date(2017, 12, 8),
    jobs: { construction: 30000, operation: 2000, localShare: 0.7 },
    co2KtPerYear: 5000,
    landHa: 1500,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Yamal_LNG', 'Silk_Road_Fund'),
  },
  {
    // Negotiated since the mid-2000s and signed in May 2014 as a Gazprom–CNPC supply
    // contract; Gazprom financed the Russian line and no Chinese policy-bank loan or BRI
    // fund is involved, so it would exist without the BRI.
    id: 'power-of-siberia',
    kind: 'pipeline',
    country: 'RUS',
    region: 'RUS-SIB',
    bri: false,
    sponsor: 'RUS',
    lenders: [],
    costBn: 55,
    loanBn: 0,
    interestRate: 0,
    announced: date(2014, 5, 21),
    constructionStart: date(2014, 9, 1),
    opened: date(2019, 12, 2),
    jobs: { construction: 10000, operation: 1500, localShare: 0.95 },
    co2KtPerYear: 1000,
    landHa: 6500,
    displacedPeople: 0,
    opensLinks: ['zabaykalsk~beijing~pipeline'],
    provenance: 'estimated',
    source: wiki('Power_of_Siberia'),
  },
  {
    // Contracted to a CRCC-led consortium with a China Exim loan in the mid-2000s, before
    // the BRI, so it is kept in the no-BRI world.
    id: 'ankara-istanbul-hsr',
    kind: 'rail',
    country: 'TUR',
    region: 'TUR-REST',
    bri: false,
    sponsor: 'CHN',
    lenders: ['china-exim'],
    costBn: 1.27,
    loanBn: 0.72,
    interestRate: 0.03,
    announced: date(2005, 10, 1),
    constructionStart: date(2008, 1, 1),
    opened: date(2014, 7, 25),
    jobs: { construction: 8000, operation: 500, localShare: 0.85 },
    co2KtPerYear: 10,
    landHa: 600,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Ankara–Istanbul_high-speed_railway'),
  },
  {
    id: 'kumport-terminal',
    kind: 'port',
    country: 'TUR',
    region: 'TUR-IST',
    bri: true,
    sponsor: 'CHN',
    lenders: [],
    costBn: 0.94,
    loanBn: 0,
    interestRate: 0,
    announced: date(2015, 9, 16),
    constructionStart: date(2015, 9, 16),
    opened: date(2015, 12, 1),
    jobs: { construction: 300, operation: 1000, localShare: 0.98 },
    co2KtPerYear: 40,
    landHa: 0,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Ambarlı', 'COSCO_Shipping_Ports', 'China_Merchants_Port'),
  },
  {
    id: 'nac-cbd',
    kind: 'urban',
    country: 'EGY',
    region: 'EGY-CAI',
    bri: true,
    sponsor: 'CHN',
    lenders: ['icbc'],
    costBn: 3,
    loanBn: 2.55,
    interestRate: 0.045,
    announced: date(2017, 10, 11),
    constructionStart: date(2018, 5, 1),
    jobs: { construction: 30000, operation: 2000, localShare: 0.95 },
    co2KtPerYear: 40,
    landHa: 50,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('New_Administrative_Capital', 'Iconic_Tower_(Egypt)'),
  },
  {
    id: 'teda-suez-zone',
    kind: 'industrial-zone',
    country: 'EGY',
    region: 'EGY-SCZ',
    bri: true,
    sponsor: 'CHN',
    lenders: [],
    costBn: 0.23,
    loanBn: 0,
    interestRate: 0,
    announced: date(2016, 1, 21),
    constructionStart: date(2016, 1, 21),
    opened: date(2018, 1, 1),
    jobs: { construction: 2000, operation: 4000, localShare: 0.9 },
    co2KtPerYear: 300,
    landHa: 600,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Suez_Canal_Economic_Zone', 'Ain_Sokhna'),
  },
  {
    id: 'tehran-mashhad-electrification',
    kind: 'rail',
    country: 'IRN',
    region: 'IRN-REST',
    bri: true,
    sponsor: 'CHN',
    lenders: ['china-exim'],
    costBn: 2.1,
    loanBn: 1.5,
    interestRate: 0.03,
    announced: date(2016, 1, 23),
    constructionStart: date(2016, 2, 4),
    jobs: { construction: 3000, operation: 300, localShare: 0.85 },
    co2KtPerYear: 0,
    landHa: 50,
    displacedPeople: 0,
    opensLinks: [],
    provenance: 'estimated',
    source: wiki('Rail_transport_in_Iran'),
  },
  {
    id: 'marmaray',
    kind: 'rail',
    country: 'TUR',
    region: 'TUR-IST',
    bri: false,
    sponsor: 'JPN',
    lenders: ['jbic', 'eib'],
    costBn: 4.5,
    loanBn: 3,
    interestRate: 0.02,
    announced: date(1999, 9, 17),
    constructionStart: date(2004, 5, 9),
    opened: date(2013, 10, 29),
    jobs: { construction: 5000, operation: 1000, localShare: 1 },
    co2KtPerYear: 5,
    landHa: 30,
    displacedPeople: 0,
    opensLinks: ['istanbul~budapest~rail'],
    provenance: 'estimated',
    source: wiki('Marmaray'),
  },
];
